version: "3.9"

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-import
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: targetdb
      MARIADB_USER: target_user
      MARIADB_PASSWORD: target_password
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
