spring:
  application:
    name: template

  datasource:
    url: jdbc:mariadb://localhost:3309/targetdb
    username: target_user
    password: target_password
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: false

  jdbc:
    template:
      fetch-size: 1000

logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO

import:
  enabled: true

  # File locations
  incoming-dir: ./files/incoming
  processed-dir: ./files/processed
  failed-dir: ./files/failed
  temp-download-dir: ./files

  # Expected file names
  org-file-name: OrgExport.csv
  emp-file-name: EmpExport.csv

  # Batch size
  batch-size: 200

scheduler:
  scheduled-org-import:
    cron: "0 */2 * * * *"
    name: "org-import"
    shedlock-lock-at-most-for: "PT2H"
    maximum-execution-time: "PT2H"

  scheduled-emp-import:
    cron: "30 */2 * * * *"
    name: "emp-import"
    shedlock-lock-at-most-for: "PT2H"
    maximum-execution-time: "PT2H"

server:
  port: 8081

openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
